name: chat_app1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"   # use a proper Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.1.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^19.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# CLI tools (not runtime)
dependency_overrides:
  flutterfire_cli: ^1.3.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21